services:
  booking_service:
    container_name: 'booking_service_container'
    build:
      context: .
    ports: 
      - "8888:8000"   
    networks:
      - network
    env_file:
      - .env

  booking_celery_worker:
    container_name: 'booking_celery_worker_container'
    build:
      context: .
    networks:
      - network      
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance worker -l INFO --pool=solo"

  booking_celery_beat:
    container_name: 'booking_celery_beat_container'
    build:
      context: .  
    networks:
      - network
    env_file:
      - .env
    command: "celery --app=src.tasks.celery_app:celery_instance beat -l INFO"

networks: 
  network:
    external: true